// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pw.Hub.Relics.Infrastructure.Data;

#nullable disable

namespace Pw.Hub.Relics.Infrastructure.Migrations
{
    [DbContext(typeof(RelicsDbContext))]
    [Migration("20260220120616_RemoveTelegramChatIdFromNotificationFilters")]
    partial class RemoveTelegramChatIdFromNotificationFilters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pw.Hub.Relics.Domain.Entities.AttributeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("attribute_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Физическая атака"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Магическая атака"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Защита"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Магическая защита"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Здоровье"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Мана"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Меткость"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Уклонение"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Показатель атаки"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Показатель защиты"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Боевой дух"
                        });
                });

            modelBuilder.Entity("Pw.Hub.Relics.Domain.Entities.EnhancementCurve", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("RequiredExperience")
                        .HasColumnType("integer")
                        .HasColumnName("required_experience");

                    b.HasKey("Level");

                    b.ToTable("enhancement_curve", (string)null);

                    b.HasData(
                        new
                        {
                            Level = 1,
                            RequiredExperience = 200
                        },
                        new
                        {
                            Level = 2,
                            RequiredExperience = 275
                        },
                        new
                        {
                            Level = 3,
                            RequiredExperience = 400
                        },
                        new
                        {
                            Level = 4,
                            RequiredExperience = 625
                        },
                        new
                        {
                            Level = 5,
                            RequiredExperience = 900
                        },
                        new
                        {
                            Level = 6,
                            RequiredExperience = 1200
                        },
                        new
                        {
                            Level = 7,
                            RequiredExperience = 1775
                        },
                        new
                        {
                            Level = 8,
                            RequiredExperience = 2625
                        },
                        new
                        {
                            Level = 9,
                            RequiredExperience = 3675
                        },
                        new
                        {
                            Level = 10,
                            RequiredExperience = 5725
                        },
                        new
                        {
                            Level = 11,
                            RequiredExperience = 7450
                        },
                        new
                        {
                            Level = 12,
                            RequiredExperience = 10150
                        },
                        new
                        {
                            Level = 13,
                            RequiredExperience = 14125
                        },
                        new
                        {
                            Level = 14,
                            RequiredExperience = 18075
                        },
                        new
                        {
                            Level = 15,
                            RequiredExperience = 23530
                        },
                        new
                        {
                            Level = 16,
                            RequiredExperience = 29270
                        },
                        new
                        {
                            Level = 17,
                            RequiredExperience = 31050
                        },
                        new
                        {
                            Level = 18,
                            RequiredExperience = 35100
                        },
                        new
                        {
                            Level = 19,
                            RequiredExperience = 39025
                        },
                        new
                        {
                            Level = 20,
                            RequiredExperience = 44825
                        });
                });

            modelBuilder.Entity("Pw.Hub.Relics.Domain.Entities.NotificationFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<int?>("MainAttributeId")
                        .HasColumnType("integer")
                        .HasColumnName("main_attribute_id");

                    b.Property<long?>("MaxPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("max_price");

                    b.Property<long?>("MinPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("min_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int?>("Race")
                        .HasColumnType("integer")
                        .HasColumnName("race");

                    b.PrimitiveCollection<List<int>>("RequiredAdditionalAttributeIds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("required_additional_attribute_ids");

                    b.Property<int?>("ServerId")
                        .HasColumnType("integer")
                        .HasColumnName("server_id");

                    b.Property<int?>("SlotTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type_id");

                    b.Property<int?>("SoulLevel")
                        .HasColumnType("integer")
                        .HasColumnName("soul_level");

                    b.Property<int?>("SoulType")
                        .HasColumnType("integer")
                        .HasColumnName("soul_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsEnabled");

                    b.ToTable("notification_filters", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Relics.Domain.Entities.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.PrimitiveCollection<List<int>>("AdditionalAttributeIds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("additional_attribute_ids");

                    b.Property<int>("MainAttributeId")
                        .HasColumnType("integer")
                        .HasColumnName("main_attribute_id");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<int>("RelicDefinitionId")
                        .HasColumnType("integer")
                        .HasColumnName("relic_definition_id");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer")
                        .HasColumnName("server_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalAttributeIds");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AdditionalAttributeIds"), "gin");

                    b.HasIndex("MainAttributeId");

                    b.HasIndex("RelicDefinitionId");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.ToTable("price_history", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Relics.Domain.Entities.RelicAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("integer")
                        .HasColumnName("attribute_definition_id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<Guid>("RelicListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("relic_listing_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("Category");

                    b.HasIndex("RelicListingId");

                    b.ToTable("relic_attributes", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Relics.Domain.Entities.RelicDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("IconUri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_uri");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Race")
                        .HasColumnType("integer")
                        .HasColumnName("race");

                    b.Property<int>("SlotTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("slot_type_id");

                    b.Property<int>("SoulLevel")
                        .HasColumnType("integer")
                        .HasColumnName("soul_level");

                    b.Property<int>("SoulType")
                        .HasColumnType("integer")
                        .HasColumnName("soul_type");

                    b.HasKey("Id");

                    b.HasIndex("SlotTypeId");

                    b.HasIndex("SoulLevel", "SoulType", "SlotTypeId", "Race");

                    b.ToTable("relic_definitions", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Relics.Domain.Entities.RelicListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AbsorbExperience")
                        .HasColumnType("integer")
                        .HasColumnName("absorb_experience");

                    b.Property<string>("AttributesHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("attributes_hash");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("EnhancementLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("enhancement_level");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<int>("RelicDefinitionId")
                        .HasColumnType("integer")
                        .HasColumnName("relic_definition_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long>("SellerCharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("seller_character_id");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer")
                        .HasColumnName("server_id");

                    b.Property<int>("ShopPosition")
                        .HasColumnType("integer")
                        .HasColumnName("shop_position");

                    b.Property<DateTime?>("SoldAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sold_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("Price");

                    b.HasIndex("RelicDefinitionId");

                    b.HasIndex("ServerId");

                    b.HasIndex("IsActive", "CreatedAt")
                        .HasFilter("is_active = TRUE");

                    b.HasIndex("SellerCharacterId", "ShopPosition", "ServerId", "RelicDefinitionId")
                        .IsUnique();

                    b.HasIndex("ServerId", "SellerCharacterId", "ShopPosition", "AttributesHash")
                        .HasDatabaseName("IX_RelicListings_Lookup");

                    b.ToTable("relic_listings", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Relics.Domain.Entities.ServerDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("server_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Key = "centaur",
                            Name = "Центавр"
                        },
                        new
                        {
                            Id = 3,
                            Key = "alkor",
                            Name = "Алькор"
                        },
                        new
                        {
                            Id = 5,
                            Key = "mizar",
                            Name = "Мицар"
                        },
                        new
                        {
                            Id = 29,
                            Key = "capella",
                            Name = "Капелла"
                        });
                });

            modelBuilder.Entity("Pw.Hub.Relics.Domain.Entities.SlotType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("slot_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Цветок сострадания"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Самоцвет скромности"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Зеркало честности"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Замок дисциплины"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Колокол праведности"
                        });
                });

            modelBuilder.Entity("Pw.Hub.Relics.Domain.Entities.TelegramBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_confirmed");

                    b.Property<string>("LinkToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("link_token");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("telegram_username");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_expires_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LinkToken")
                        .IsUnique();

                    b.HasIndex("TelegramChatId")
                        .IsUnique()
                        .HasFilter("telegram_chat_id IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("telegram_bindings", (string)null);
                });

            modelBuilder.Entity("Pw.Hub.Relics.Domain.Entities.RelicAttribute", b =>
                {
                    b.HasOne("Pw.Hub.Relics.Domain.Entities.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pw.Hub.Relics.Domain.Entities.RelicListing", null)
                        .WithMany("Attributes")
                        .HasForeignKey("RelicListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");
                });

            modelBuilder.Entity("Pw.Hub.Relics.Domain.Entities.RelicDefinition", b =>
                {
                    b.HasOne("Pw.Hub.Relics.Domain.Entities.SlotType", "SlotType")
                        .WithMany()
                        .HasForeignKey("SlotTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SlotType");
                });

            modelBuilder.Entity("Pw.Hub.Relics.Domain.Entities.RelicListing", b =>
                {
                    b.HasOne("Pw.Hub.Relics.Domain.Entities.RelicDefinition", "RelicDefinition")
                        .WithMany()
                        .HasForeignKey("RelicDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pw.Hub.Relics.Domain.Entities.ServerDefinition", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RelicDefinition");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("Pw.Hub.Relics.Domain.Entities.RelicListing", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
